const data = {
    products: [
        {
            id : '1',
            name : 'Nike Slim Shirt',
            category : 'Shirts',
            image : '/images/p1.jpg',
            price : '120',
            countInStock : 10,
            brand : 'Nike',
            rating : 4.5,
            numReviews : 10,
            description : 'High quality product',
        },
        {
            id : '2',
            name : 'Adidas Slim Shirt',
            category : 'Shirts',
            image : '/images/p2.jpg',
            price : '115',
            countInStock : 20,
            brand : 'Adida15',
            rating : 4.5,
            numReviews : 10,
            description : 'High quality product',
        },
        {
            id : '3',
            name : 'Roadster Slim Shirt',
            category : 'Shirts',
            image : '/images/p3.jpg',
            price : '100',
            countInStock : 0,
            brand : 'Roadster',
            rating : 5,
            numReviews : 10,
            description : 'High quality product',
        },
        {
            id : '4',
            name : 'Cambridge Formal Trousers',
            category : 'Trousers',
            image : '/images/p4.jpg',
            price : '130',
            countInStock : 5,
            brand : 'Cambridge',
            rating : 4,
            numReviews : 8,
            description : 'High quality product',
        },
        {
            id : '5',
            name : 'Zara Casual Trousers',
            category : 'Trousers',
            image : '/images/p5.jpg',
            price : '105',
            countInStock : 20,
            brand : 'Zara',
            rating : 5,
            numReviews : 12,
            description : 'High quality product',
        },
        {
            id : '6',
            name : 'FabIndia Formal Trouser',
            category : 'Trousers',
            image : '/images/p6.jpg',
            price : '110',
            countInStock : 10,
            brand : 'FabIndia',
            rating : 5,
            numReviews : 10,
            description : 'High quality product',
        },
    ]
}

export default data;